version: "3.8"

services:
  app:
    image: php:8.2-apache
    container_name: invitaciond-a-app
    volumes:
      - ./html:/var/www/html
    ports:
      - "8080:80"
    command: apache2-foreground

